We will use the autograd function in the MXNet framework, thus all data going through the computation graph should be `ndarrays`.
In this notebook you will learn the basics of the NumPy package and MXNet's extensions to it.

To get started, let's import the numpy namespace from MXNet as `np`. For the most parts, you can use it as ordinary `numpy`.

In [1]:
import mxnet as mx
from mxnet import np, npx
import numpy as onp

### Create arrays
Let's see how to create a 2-D array with values from two sets of numbers: 1, 2, 3 and 4, 5, 6.
For the homework we will do everything on a CPU so we don't have to specify the `ctx` argument.

In [3]:
# set ctx=mx.gpu(0) to create one on a GPU
a = np.array(((1,2,3),(4,5,6)), ctx=mx.cpu())
a

array([[1., 2., 3.],
       [4., 5., 6.]])

### Inspect an ndarray's attributes
As with NumPy, the dimensions of each ndarray are accessible by accessing the .shape attribute. We can also query its size, which is equal to the product of the components of the shape. In addition, .dtype tells the data type of the stored values.

In [4]:
(a.shape, a.size, a.dtype, a.context)

((2, 3), 6, dtype('float32'), cpu(0))

### Create a 2-D Array of Ones
We can also create a very simple matrix with the same shape (2 rows by 3 columns), but fill it with 1s.

In [5]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### Create an Array of Random Values
Often we’ll want to create arrays whose values are sampled randomly. For example, sampling values uniformly between -1 and 1. Here we create the same shape, but with random sampling.

In [6]:
rand_uniform = np.random.uniform(-1,1,size=(3,3))
rand_uniform

array([[ 0.09762704,  0.18568921,  0.43037868],
       [ 0.6885315 ,  0.20552671,  0.71589124],
       [ 0.08976638,  0.6945034 , -0.15269041]])

### Array indexing
Here’s an example of reading a particular element, which returns a 1D array with shape (1,).

In [7]:
a[1,2]

array(6.)

In [8]:
a[:,1:3]

array([[2., 3.],
       [5., 6.]])

In [9]:
a[-1]

array([4., 5., 6.])

In [12]:
a[:,1:3] = 2
a

array([[1., 2., 2.],
       [4., 2., 2.]])

In [13]:
a[1:2,0:2] = 4
a

array([[1., 2., 2.],
       [4., 4., 2.]])

### Converting between MXNet and NumPy
Converting MXNet ndarrays to and from NumPy is easy.

In [14]:
a_np = a.asnumpy()
type(a_np)

numpy.ndarray

We can also convert NumPy arrays to MXNet.


In [15]:
type(npx.from_numpy(a_np))

mxnet.numpy.ndarray

### Check for documentation of a function
Type "?" after a function to check its documentation.

In [17]:
np.equal?

Signature: np.equal(x1, x2, out=None)
Docstring:
Return (x1 == x2) element-wise.
Parameters
----------
x1, x2 : ndarrays or scalars
    Input arrays. If ``x1.shape != x2.shape``, they must be broadcastable to
    a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned.
Returns
-------
out : ndarray or scalar
    Output array of type bool, element-wise comparison of `x1` and `x2`.
    This is a scalar if both `x1` and `x2` are scalars.
See Also
--------
not_equal, greater_equal, less_equal, greater, less
Examples
--------
>>> np.equal(np.ones(2, 1)), np.zeros(1, 3))
array([[False, False, False],
       [False, False, False]])
>>> np.equal(1, np.ones(1))
array([ True])
File:      ~/mxnet/python/mxnet/numpy/multiarray.py
Type:      function


### Useful functions for the homework

Check if two arrays are equal.

In [18]:
b = np.array([1,2,3])
np.equal(a[0, :], b)

array([ True,  True, False])

In [25]:
b = np.expand_dims(a, 1)
b.shape
b
a

array([[1., 2., 2.],
       [4., 4., 2.]])

In [21]:
np.expand_dims?

Signature: np.expand_dims(a, axis)
Docstring:
Expand the shape of an array.

Insert a new axis that will appear at the `axis` position in the expanded array shape.

Parameters
----------
a : ndarray
    Input array.
axis : int
    Position in the expanded axes where the new axis is placed.

Returns
-------
res : ndarray
    Output array. The number of dimensions is one greater than that of
    the input array.

See Also
--------
squeeze : The inverse operation, removing singleton dimensions
reshape : Insert, remove, and combine dimensions, and resize existing ones

Examples
--------
>>> x = np.array([1,2])
>>> x.shape
(2,)

>>> y = np.expand_dims(x, axis=0)
>>> y
array([[1., 2.]])

>>> y.shape
(1, 2)

>>> y = np.expand_dims(x, axis=1)  # Equivalent to x[:,np.newaxis]
>>> y
array([[1.],
       [2.]])

>>> y.shape
(2, 1)

Note that some examples may use None instead of np.newaxis. These are the same objects:

>>> np.newaxis is None
True
File:      ~/mxnet/python/mxnet/numpy/multiarray.py

In [26]:
np.vstack?

Signature: np.vstack(arrays, out=None)
Docstring:
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate` and `stack`
provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 2-D.

Examples
--------
>>> a = np.array([1, 2, 3])
>>> b = np.array([2, 3, 4])
>>> np.vstack((a, b))
array([[1., 2., 3.],
       [2., 3., 4.]])

>>> a = np.array([[1], [2], [3]])
>>> b = np.array([[